// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4GM0oLLT3Kpew4IVplcZ6vxQjodeHj1Y',
    appId: '1:87414724762:web:8359770ccf084c2204a723',
    messagingSenderId: '87414724762',
    projectId: 'booqlyapp-83777',
    authDomain: 'booqlyapp-83777.firebaseapp.com',
    storageBucket: 'booqlyapp-83777.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDys4sD_y_YSfBbHkvLm1BRGTLZ2nqSvXA',
    appId: '1:87414724762:android:c3375c524ad25da404a723',
    messagingSenderId: '87414724762',
    projectId: 'booqlyapp-83777',
    storageBucket: 'booqlyapp-83777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjEzjShU7n_AJI9YEOUswFRGbldKXV_Ag',
    appId: '1:87414724762:ios:f98652b95b961cf304a723',
    messagingSenderId: '87414724762',
    projectId: 'booqlyapp-83777',
    storageBucket: 'booqlyapp-83777.firebasestorage.app',
    iosBundleId: 'com.example.booqly',
  );
}
